[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.12.1"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_DISABLE_ETW = "1"
  NEXT_SKIP_API_DIRECTORY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
